/**
 * Error codes used throughout the application
 */
export enum ErrorCode {
  // Data Loading Errors
  DATA_FILE_NOT_FOUND = 'DATA_FILE_NOT_FOUND',
  DATA_PARSE_ERROR = 'DATA_PARSE_ERROR',
  DATA_SCHEMA_INVALID = 'DATA_SCHEMA_INVALID',

  // Search Errors
  SEARCH_INVALID_QUERY = 'SEARCH_INVALID_QUERY',
  SEARCH_MISSING_DEPENDENCIES = 'SEARCH_MISSING_DEPENDENCIES',
  SEARCH_OPERATION_FAILED = 'SEARCH_OPERATION_FAILED',

  // Validation Errors
  VALIDATION_INVALID_PAGINATION = 'VALIDATION_INVALID_PAGINATION',
  VALIDATION_INVALID_OPTIONS = 'VALIDATION_INVALID_OPTIONS',
  VALIDATION_INVALID_VERSE_STRUCTURE = 'VALIDATION_INVALID_VERSE_STRUCTURE',

  // Tokenization Errors
  TOKENIZATION_MISSING_MORPHOLOGY = 'TOKENIZATION_MISSING_MORPHOLOGY',
  TOKENIZATION_INVALID_MODE = 'TOKENIZATION_INVALID_MODE',
  TOKENIZATION_MISSING_WORD_MAP = 'TOKENIZATION_MISSING_WORD_MAP',
}

/**
 * Error types for categorizing errors
 */
export enum ErrorType {
  DATA_ERROR = 'DataError',
  SEARCH_ERROR = 'SearchError',
  VALIDATION_ERROR = 'ValidationError',
  TOKENIZATION_ERROR = 'TokenizationError',
}
